version: '3.8'

services:
  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    container_name: question-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: user-service

  matching-service:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: matching-service
    environment:
      RABBITMQ_URL: "amqp://rabbitmq:5672"  # RabbitMQ service name from the compose file
    depends_on:
      - rabbitmq
    networks:
      - peerprep_network
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    #networks:
    #  - peerprep_network
  
#networks:
 # peerprep_network:
  #  external: true