version: '3.8'

services:
  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
